gallery/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import upload, specific_image, save_rotated_image

app_name = 'gallery'
urlpatterns = [
    path('', upload, name='upload'),
    path('image/<int:pk>/', specific_image, name='specific_image'),
    path('saverotatedimage/', save_rotated_image, name='save_rotated_image'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorbin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls', namespace='gallery')),
]

gallery/models.py
from django.db import models
from taggit.managers import TaggableManager


# Create your models here.
class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    tags = TaggableManager()    

gallery/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from PIL import Image as PilImage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Image


def is_ajax(self):
    # check whether the request is ajax, replacement of default is_ajax method
    return self.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"


def upload(request):

    # if this is a POST request we need to process the form data
    if request.method == "POST":
        images = request.FILES.getlist('images')
        tags = request.POST.getlist('tags')
        for image in images:
            image_object = Image.objects.create(image=image)
            for tag in tags:
                image_object.tags.add(tag)

    # handle AJAX Call
    if is_ajax(request):
        tag_list = request.GET.get('value').split(',')
        if tag_list[0] == '':
            filtered_image = Image.objects.all()
        else:
            filtered_image = Image.objects.filter(tags__name__in=tag_list)
        image_urls = [p.image.url for p in filtered_image]
        # print(image_urls)
        return JsonResponse({'data': image_urls })

    images = Image.objects.all()
    tags = Image.tags.all()
    page = request.GET.get('page', 1)

    # pagination for 8 images per page
    paginator = Paginator(images, 8)
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        images = paginator.page(paginator.num_pages)
        
    return render(request, 'index.html', {'images': images, 'tags': tags})


def specific_image(request, pk):
    # filter images by pk
    image = Image.objects.get(id = pk)
    
    return render(request, 'specific_image.html', {'image': image})


def save_rotated_image(request):
    # rotation value and image id
    rotationAmt = request.GET.get('value')
    image_id = request.GET.get('image_id')

     #getting instance of the model
    item=Image.objects.get(pk=image_id)

    #opening image for PIL to access
    im = PilImage.open(item.image)

    #rotating it by built in PIL command
    rotated_image = im.rotate(-int(rotationAmt), PilImage.NEAREST, expand = True)

    #saving rotated image instead of original. Overwriting is on. 
    rotated_image.save(item.image.file.name, overwrite=True)

    return HttpResponse(str(item.image))
  

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Mutliple Upload Image</title>
    <style>
        img {
            height: 200px;
            width: 200px;
        }
    </style>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="images" multiple>
        
        <select name="tags" multiple>
        
        {% for tag in tags %}
        <option value="{{ tag.name }}"> {{ tag.name }} </option>
        {% endfor %}

        </select>

        <button type="submit">Upload Multiple Images</button>
    </form>
    <hr>
        {% for tag in tags %}
        <input  class="selection-box" type="checkbox" id="{{ tag.name }}" name="{{ tag.name }}" value="{{ tag.name }}">
        <label for="{{ tag.name }}"> {{ tag.name }}</label>
        {% endfor %}
        <br>
    <hr>
    <div class="allimage">
        {% for img in images %}
            <a href='{% url "gallery:specific_image"  img.pk  %}' target="_blank"> 
                <img id="allimg" src="{{img.image.url}}" alt="Image">
            </a>
        {% endfor %}

        <hr>
        {% if images.has_other_pages %}
        <ul >
            {% if images.has_previous %}
            <li><a href="?page={{ images.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in images.paginator.page_range %}
            {% if images.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if images.has_next %}
            <li><a href="?page={{ images.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
    <hr>
    <!-- filtered image will append here-->
    <div class ="filterimage">

    </div>

    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {

            // catch the form's submit event
            $('.selection-box').on('change',function () {

                var matches = '';
                var count = 0;

                // loop through all checkboxes
                $(".selection-box:checked").each(function() {
                    // if at least one checkbox is checked
                    if (count>0){
                        matches += ',' + this.value;
                    }
                    else{
                        matches+=this.value
                    }
                    count+=1
                });

                // data to be sent with ajax
                var ajax_get_data = {
                    "value": matches
                }

                // create an AJAX call
                $.ajax({
                    data: ajax_get_data, // get the form data
                    url: "{% url 'gallery:upload' %}",
                    headers: {
                        "X-Requested-With": "XMLHttpRequest",
                    },

                    // on success
                    success: function (response) {
                        
                        var pictures = response.data;

                        // check response data length then show all image gallery according to condition
                        if(pictures.length>0){
                            $('.allimage').hide();
                        }
                        else{

                            $('.allimage').show();
                            $('p#filterimage').remove();
                        }
                        // make pre-append div container empty for new response
                         $('div.filterimage').empty();
                        // Iterate over all picture and append inside single container
                         for (const [key, value] of Object.entries(pictures)) {
                           // image tag string
                            var img = '<a href="/image/'+key+'/" target="_blank" > <img src="'+ value +'" alt="Image" > </a>';
                            
                            $('div.filterimage').append(img);
                        }
                        $('div.filterimage').append("<p id='filterimage'> Filtered images</p>");       
                    },
                    // on error
                    error: function (response) {
                        // alert the error if any error occured
                        console.log(response.responseJSON.errors)
                    }
                });
                return false;
            });
        })
    </script>
    {% endblock javascript %}
</body>
</html>

templates/specific_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Specific Image</title>
</head>
<body>
  
    <img id="img" src="{{ image.image.url}}"/>

    <button onclick="negrotate()">-90 deg</button>
    <button onclick="posrotate()">+90 deg</button>
    <button onclick="saveimage({{ image.id}})">Save Rotated Image</button>
    <div class ="filterimage">

    </div>

    {% block javascript %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>

    var rotate_value = 0;

    function negrotate() {
        // function to rotate image -90 degrees

        rotate_value -= 90;
        
        document.querySelector("#img").style.transform = "rotate(" + rotate_value.toString() + "deg)";
    }
    function posrotate() {
        // function to rotate image +90 degrees

        rotate_value += 90;
        
        document.querySelector("#img").style.transform = "rotate(" + rotate_value.toString() + "deg)";
    }

    function  saveimage(image_id) {
            
        // ajax_call data 
        var ajax_get_data = {
            "value": rotate_value,
            "image_id": image_id
            }

        $.ajax({
                data: ajax_get_data, // get the form data
                url: "{% url 'gallery:save_rotated_image' %}",
                headers: {
                    "X-Requested-With": "XMLHttpRequest",
                },
                // on success
                success: function (response) {
                    // reinitialize the rotate_value
                    rotate_value = 0;
                    $('div.filterimage').append("<p id='filterimage'> Successfully Rotated, Refresh the page to verify results</p>"); 
                
                },
                // on error
                error: function (response) {
                    // alert the error if any error occured
                    console.log(response.responseJSON.errors)
                }
            });
        }
    </script>
    {% endblock javascript %}
</body>
</html>